### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by pikes4ever** [PoomSmart/LetMeBlock#1]
unc0ver 3.00 b33 and hosts file is still ignored

**Comment by KhafraDev** [comment]
Try running "killall -9 mDNSResponder" in terminal/SSH.

**Comment by pikes4ever** [comment]
That did fix the issue. Tried it twice to confirm

**Comment by PoomSmart** [comment]
If it doesn't work, it's because LetMeBlock has yet to be loaded to `mDNSResponder`. One has to manually do `killall -9 mDNSResponder`.
