### ISSUE TITLE
Hosts are still ignored

### ISSUE THREAD

**Issue by Arrow-Li** [PoomSmart/LetMeBlock#10]
iP7, iOS 12.4, unc0ver
Already reinstalling LetMeBlock from Cydia many times.
![99](https://user-images.githubusercontent.com/17962902/63827427-a8c05d80-c995-11e9-8b7c-9b6282c5a544.png)

**Comment by PoomSmart** [comment]
This rather has something to do with `bing.com` and not LMB because there's no way it won't work unless you have (Mega) UHB installed which will entirely ignore the original host file.

**Comment by Arrow-Li** [comment]
Hosts works when update to 0.0.7.1
