### ISSUE TITLE
The hosts file is being partially ignored

### ISSUE THREAD

**Issue by nik312123** [PoomSmart/LetMeBlock#11]
In the hosts file, I have the following lines at the bottom:
0 ifunny.co
0 reddit.com
0 quora.com

I did the following steps in the order written:

1. I killed mDNSResponder and mDNSResponderHelper.
2. I reinstalled LetMeBlock from Cydia.
3. I killed mDNSResponder and mDNSResponderHelper again just in case.
4. I rebooted my device.
5. I rejailbroke via unc0ver.

Doing this, I can not access ifunny.co anymore, but I can access reddit.com and quora.com.

My LetMeBlock version is 0.0.6.8. I am on iOS 12.4 on an iPhone 6S. My unc0ver version is 3.7.0~b1.

Please let me know if any additional details would be helpful.

**Comment by PoomSmart** [comment]
As far as I can tell that’s something to do with the hosts you have; blocking reddit may require additional hosts. What LMB does is to make iOS care about hosts file, no whitelist whatsoever.
