### ISSUE TITLE
LetMeBlock 0.0.7.3 

### ISSUE THREAD

**Issue by CecilioSoto** [PoomSmart/LetMeBlock#14]
I updated LetMeBlockton August 16,2020 1:10 a.m. to 0.0.7.3 and it disabled my cellular data and  WiFi  on my iPhone 11 Pro iOS 13.5. I had to downgrade to 0.0.7.1. And now my data and WiFi work again. Thanks!

**Comment by mattp12** [comment]
Happening over here as well. 8 Plus, checkra1n iOS 13.6.1

**Comment by PoomSmart** [comment]
Fixed in 0.0.7.4
