### ISSUE TITLE
hosts are still ignored

### ISSUE THREAD

**Issue by mikigal** [PoomSmart/LetMeBlock#2]
/etc/hosts is still ignored, tried killall mDNSresolver, clean with iCleaner Pro. 
iOS 12, unc0ver b33, disabled reload system daemons

**Comment by PoomSmart** [comment]
Isn't it `mDNSResponder` ?
Try `killall -9 mDNSResponder`.

**Comment by mikigal** [comment]
Yeah, it was. Stupid typo. I tried your command. After execute it two times I get message that this process does not exists so mDNSResponder was killed. Bo without any effect

**Comment by PoomSmart** [comment]
You only need to execute it one time and it will work. If not, try *reinstalling* LetMeBlock from Cydia.

**Comment by mikigal** [comment]
Reinstall helped, thanks!
