### ISSUE TITLE
No effect on Dopamine device?

### ISSUE THREAD

**Issue by jebediah2** [PoomSmart/LetMeBlock#20]
Very strange that nothing seems to happen after I run a test on an iPhone 13 Mini 15.4.1 with Dopamine.

- Install LetMeBlock
- In Filza, create hosts file in /var/jb/etc/ with an example.com entry
- Reboot userspace
- Example.com is reachable in Safari
- Reinstall LetMeBlock
- Reboot userspace
- Example.com still reachable

the hosts file:
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost

127.0.0.1 example.com
0 example.com
0.0.0.0 example.com

Is there something I'm doing wrong?

**Comment by PoomSmart** [comment]
Your LetMeBlock version?

**Comment by jebediah2** [comment]
1.1.0 freshly installed from your repo.

**Comment by PoomSmart** [comment]
1. Any jailbreak detection bypass tweaks installed?
2. What if you reinstall LetMeBlock from your package manager without doing userspace reboot?

**Comment by jebediah2** [comment]
I had shadow installed but it wasn't enabled. I uninstalled it nonetheless then reinstalled LetMeBlock, but it didn't change anything.
Tried your suggestion to only perform the SpringBoard restart (and to skip it altogether) after reinstalling LetMeBlock, but results are the same.

**Comment by jebediah2** [comment]
Is there nay chance adblocker apps interfere? I've got AdBlock, AdBlock Pro and AdGuard Pro installed.

**Comment by jebediah2** [comment]
@PoomSmart have you looked into this at all?

**Comment by jebediah2** [comment]
I noticed that when I run `killall -9 mDNSResponder` as root, it works fine. But when I run the same for `mDNSResponderHelper` I get **No matching processes were found**

Also, when I replace the hosts file in var/jb/etc/ with my own, which weighs a few megabytes, I can no longer access the internet altogether.

**Comment by PoomSmart** [comment]
The issue with `/var/jb/etc/hosts` not being read is fixed in v1.2.0

**Comment by jebediah2** [comment]
Fantastic! Thanks for the fix.
