### ISSUE TITLE
Memory Limit and jetsam crashes 

### ISSUE THREAD

**Issue by 0xkuj** [PoomSmart/LetMeBlock#22]
Following the discussion that reopened here: https://github.com/PoomSmart/LetMeBlock/issues/21

have you considered of making a letmeblock version that doesn't have jetsam limit? 
Reference: https://gist.github.com/Lessica/ecfc5816467dcbaac41c50fd9074b8e9

mDNSResponder crash log attached to the above issue

**Comment by PoomSmart** [comment]
Yes I saw that snippet. Just hasn't had time to try it out.

**Comment by PoomSmart** [comment]
The snippet doesn't work. Based on my research, unless we have a way to modify the inactive hard memory limit of `mDNSResponder` (`9MB` or similar), it's not possible. `memorystatus_control` only modifies "behavior" and not the actual "memory quota".

**Comment by 0xkuj** [comment]
I tried implementing the snippet myself, the result I got is immediate crash on mDNSResponder, no matter how much memory it consumes.. what else can we try?

**Comment by PoomSmart** [comment]
Just now, I found that LetMeBlock can't actually find `mDNSResponder` so the code to apply for memory limit bypass isn't even executed..

**Comment by 0xkuj** [comment]
I think if you'll fix it, it will immediately crash as I experienced with the snippet (I used a different algo to find the mDNSResponder pid because I made it as a different executable)

**Comment by PoomSmart** [comment]
@0xkuj Can you share that algo, maybe I can try that out?

**Comment by 0xkuj** [comment]
@PoomSmart 
actually they look pretty much the same :/

```
pid_t getMDNSResponderPID() {
    pid_t mDNSResponderPID = 0;
    int mib[4] = {CTL_KERN, KERN_PROC, KERN_PROC_ALL, 0};
    size_t size;

    if (sysctl(mib, 4, NULL, &size, NULL, 0) != -1) {
        struct kinfo_proc *processes = (struct kinfo_proc *)malloc(size);
        if (processes) {
            if (sysctl(mib, 4, processes, &size, NULL, 0) != -1) {
                for (unsigned long i = 0; i < size / sizeof(struct kinfo_proc); ++i) {
                    if (strcmp(processes[i].kp_proc.p_comm, "mDNSResponder") == 0) {
                        mDNSResponderPID = processes[i].kp_proc.p_pid;
                        break;
                    }
                }
            }
            free(processes);
        }
    }

    return mDNSResponderPID;
}
```


i also uploaded my attempt here:
basically run the snippet as a helper binary:
https://github.com/0xkuj/LetMeBlockNOJETSAMTEST

**Comment by PoomSmart** [comment]
@0xkuj I may have discovered another technique to get `mDNSResponder` pid from `mDNSResponderHelper`. I pushed the latest commit. Could you try that out?

It's worth noting that some of the commands from the snippet will not work. I simply removed those, the remaining seem to work on my device.

You may have to modify the header to allow `xpc_connection_get_pid` on iOS.

**Comment by 0xkuj** [comment]
after testing it for several hours, i can tell you its working perfectly fine!
wd mate! you can go ahead and release that!
