### ISSUE TITLE
LetMeBlock Reboot Issue

### ISSUE THREAD

**Issue by ghost** [PoomSmart/LetMeBlock#3]
I updated this tweak and it rebooted my device its cause of the new update. I had to downgrade the version before rejailbreaking

**Comment by PoomSmart** [comment]
Which LetMeBlock version caused this problem?

**Comment by ghost** [comment]
same thing happened to me after installing version 0.0.3b

**Comment by ghost** [comment]
Yes it was 0.0.3b once it is upgraded it crashes your device into a unjailbroken state. Currently running iPhone X 12.1.1

**Comment by PoomSmart** [comment]
Give me details about your device.

**Comment by ghost** [comment]
currently running ios 12.1.1 b3 on an iPhone 7

**Comment by LordSlon** [comment]
after updating from cydia, need to restart the iPhone and the jailbreak broken
iPhone 8 plus, ios 12.1

**Comment by PoomSmart** [comment]
Actually, the tweak requires a single reboot after the installation. The latest version is 0.0.4 and I’m curious to know whether the issue still persists.

**Comment by ghost** [comment]
Still had to reboot after updating to 0.0.4

**Comment by ghost** [comment]
Fixed with version 0.0.4.1. Thanks!

**Comment by LordSlon** [comment]
Confirmed, 0.0.4.1. excellent install and work
