### ISSUE TITLE
Still got revoke

### ISSUE THREAD

**Issue by baobaoit** [PoomSmart/LetMeBlock#9]
Dear @PoomSmart ,

I have install this tweak and run the command `killall -9 mDNSResponder` but my modified app (YT++) is still get revoke. Although I saw that the oscp page could not connected.

My device: iPhone 6S
iOS: 12.1.1
Jailbreak tool: Chimera

Thank you.

**Comment by PoomSmart** [comment]
The tweak itself has no issues in allowing blocking hosts. Either something else prevents revocation or revocation doesn't work in the first place.
